In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
pip install gensim==4.3.1

Requirement already satisfied: gensim==4.3.1 in /usr/local/lib/python3.11/dist-packages (4.3.1)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.1) (1.26.4)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.1) (1.10.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim==4.3.1) (7.1.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim==4.3.1) (1.17.2)

In [4]:
pip install scipy==1.10.1

Requirement already satisfied: scipy==1.10.1 in /usr/local/lib/python3.11/dist-packages (1.10.1)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scipy==1.10.1) (1.26.4)

In [5]:
from gensim.models import KeyedVectors

In [6]:
model = KeyedVectors.load_word2vec_format("/content/drive/MyDrive/MED-enem/cbow_s300.txt")

In [7]:
cleaned_data = pd.read_csv("/content/drive/MyDrive/MED-enem/cleaned_data.csv")
cleaned_data.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,ano,enunciado_limpo,alternativas_limpo
0,91,Para realizar o desentupimento de tubulações d...,A: Al; B: Co; C: Cu(OH)2; D: Fe(OH)2; E: Pb,1.13773,A,2019,adicionada aumentando aumentar básico calor co...,A: al; B: co; C: cu oh; D: fe oh; E: pb
1,92,As redes de alta tensão para transmissão de en...,A: Fazer o aterramento dos arames da cerca.; B...,1.45214,A,2019,alta animais aproximarem arame campo cerca cer...,A: arames aterramento cerca fazer; B: acrescen...
2,93,A esquistossomose (barriga-dʼágua) caracteriza...,A: impedir a penetração do parasita pela pele....,0.58402,E,2019,anticorpos após barriga baseia baço biomphalar...,A: impedir parasita pele penetração; B: caramu...
3,94,"Em 1962, um jingle (vinheta musical) criado po...",A: Aquecer a casa e os corpos.; B: Evitar a en...,0.41535,C,2019,abriria animado apesar aquecer associar batia ...,A: aquecer casa corpos; B: casa corpos entrada...
4,95,Glicólise é um processo que ocorre nas células...,A: libera 112 kJ por mol de glicose.; B: liber...,2.21432,A,2019,alguns anaeróbico casos combustão completament...,A: glicose kj libera mol; B: glicose kj libera...

In [8]:
remover_palavras=[] #vetor de palavras que não compoem o corpus do modelo
enunciado_limpo_novo = [] #lista de palavras presentes no enunciado depois de limpo
remover = [',', '.', ':', ';', '(', ')'] #lista de caracteres específicos a serem retirados
lista_enunciados = [] #lista de enunciados vetorizados

for indice in range(len(cleaned_data['enunciado_limpo'])):
  #print(indice)
  enunciado_vet =[] #lista para armazenar os vetores de todas as palavras de um enunciado
  enunciado = cleaned_data['enunciado_limpo'][indice].split()

  #remove as palavras que não estão no corpus
  for palavra in remover_palavras:
    if palavra in enunciado:
      enunciado = [x for x in enunciado if x != palavra]

  for palavra in enunciado:
    #remove os caracteres indesejados
    for i in remover:
      palavra = palavra.replace(i, "")

    if palavra.lower() in model:
      enunciado_vet.append(model[palavra.lower()])
    else:
      remover_palavras.append(palavra)

    #enunciado_vet.append(model[palavra.lower()])
  lista_enunciados.append(enunciado_vet)

In [12]:
len(remover_palavras)

203

In [13]:
remover_palavras

['protanopia',
 'hidrocarbônicas',
 'calibrarem',
 'etanodiol',
 'intermembranas',
 'triprótico',
 'kônig',
 'emulsificados',
 'encapsulador',
 'nióbia',
 'cherimoia',
 'àquela',
 'hyv',
 'hoterocromalina',
 'nurchéscio',
 'redicato',
 'interconverter',
 'alquílicas',
 'ateo',
 'locoa',
 'estimulássemos',
 'excitaríamos',
 'enoico',
 'hidroxidec',
 'holometabolia',
 'planetasustentavel',
 'sedimentáveis',
 'cienciahoje',
 'indefi',
 'premenstrual',
 'reuptake',
 'hexan',
 'spneonatologia',
 'covid',
 'metilex',
 'metilpentan',
 'trimetilpentano',
 'biocarvão',
 'biochar',
 'chemmatters',
 'michalovic',
 'gazetadopovo',
 'cavagis',
 'tumorigênese',
 'dnapl',
 'canalbioenergia',
 'efundir',
 'aclimatou',
 'àquelas',
 'amínio',
 'penicilamina',
 'ogeda',
 'abocanhados',
 'nanocerâmicos',
 'demasculinized',
 'ecologically',
 'herbicide',
 'hermaphroditic',
 'collineína',
 'sanitizante',
 'sadava',
 'termogenina',
 'amonificação',
 'desnitri',
 'scienceprojectideasforkids',
 'fryhle',
 'gaultéria',
 'extinguiriam',
 'hidrolisando',
 'heteronuclear',
 'subetapa',
 'solubilizado',
 'desintoxicadas',
 'mmodelo',
 'mtorre',
 'pmodelo',
 'ptorre',
 'gastrorresistentes',
 'unifebe',
 'cianovirina',
 'viricida',
 'microbomba',
 'programaaguaazul',
 'microespectro',
 'prosab',
 'chaua',
 'cienciamao',
 'compoundchem',
 'megaespetáculos',
 'eugenioides',
 'tetraploide',
 'paleoclimatológicas',
 'eletrorrepulsão',
 'eletrosmose',
 'permeiem',
 'polionotus',
 'homogeneizá',
 'umedecê',
 'mimicry',
 'researchgate',
 'tregenza',
 'mebdownloads',
 'botal',
 'hülsendeger',
 'hyperbilirubinemia',
 'lumirrubina',
 'phototherapy',
 'astronoo',
 'catabolizados',
 'damé',
 'enegep',
 'vidauniversoydemas',
 'zalbowitz',
 'novaescola',
 'cholesteryl',
 'lysosomal',
 'semiequações',
 'alcoolômetro',
 'eletroluminescentes',
 'ngaura',
 'inovacaotecnologica',
 'canade',
 'hidrometalúrgico',
 'pirometalúrgicos',
 'eletrolisado',
 'monofluoracético',
 'estanhochumbo',
 'microvespa',
 'meselson',
 'imageiam',
 'glicocólico',
 'taurocólico',
 'remineralizando',
 'apocinaceae',
 'ithomiinae',
 'photuris',
 'polipirrol',
 'aridofolia',
 'aminometilfosfônico',
 'glicinas',
 'metilglicina',
 'sarcosina',
 'interruptora',
 'nanokid',
 'nanoputians',
 'coronopilina',
 'respectivamemente',
 'hidrogeniônicas',
 'semirreações',
 'chupanças',
 'bronzeamente',
 'lipossomo',
 'nanoemulsão',
 'triterpeno',
 'esrl',
 'ráficos',
 'eletrolisada',
 'antiumectante',
 'portalsaude',
 'trituramento',
 'lqes',
 'planetaorganico',
 'enertrag',
 'moreirajr',
 'hmáx',
 'hmín',
 'futurambiental',
 'heterozigóticas',
 'concregrama',
 'pisograma',
 'enólica',
 'semirreação',
 'wustita',
 'portaldaretina',
 'capsorubina',
 'criptoxantina',
 'dissubstituídas',
 'metilprop',
 'monossubstituídas',
 'pergaminácea',
 'calcosita',
 'nhch',
 'fácicas',
 'tetracloroguaiacol',
 'biorremediadores',
 'crapez',
 'krepsky',
 'sorventes',
 'bioabsorvível',
 'butanodioico',
 'hexanodioico',
 'cnptia',
 'sistemasdeproducao',
 'ciencianews',
 'handymath',
 'bachur',
 'trimetilxantina',
 'equimolares',
 'àquele',
 'temperaturaambiente',
 'sintonizarmos',
 'enxaguá',
 'fotocromática']

In [9]:
cleaned_data['vetor_enunciado'] = lista_enunciados

In [10]:
cleaned_data.head()

,numero_questao,enunciado,alternativas,nu_param_B,gabarito,ano,enunciado_limpo,alternativas_limpo,vetor_enunciado
0,91,Para realizar o desentupimento de tubulações d...,A: Al; B: Co; C: Cu(OH)2; D: Fe(OH)2; E: Pb,1.13773,A,2019,adicionada aumentando aumentar básico calor co...,A: al; B: co; C: cu oh; D: fe oh; E: pb,"[[-0.192243, -0.234884, -0.190927, -0.201125, ..."
1,92,As redes de alta tensão para transmissão de en...,A: Fazer o aterramento dos arames da cerca.; B...,1.45214,A,2019,alta animais aproximarem arame campo cerca cer...,A: arames aterramento cerca fazer; B: acrescen...,"[[-0.078058, -0.390552, -0.379023, 0.086376, 0..."
2,93,A esquistossomose (barriga-dʼágua) caracteriza...,A: impedir a penetração do parasita pela pele....,0.58402,E,2019,anticorpos após barriga baseia baço biomphalar...,A: impedir parasita pele penetração; B: caramu...,"[[0.202009, -0.377567, -0.509075, -0.0262, -0...."
3,94,"Em 1962, um jingle (vinheta musical) criado po...",A: Aquecer a casa e os corpos.; B: Evitar a en...,0.41535,C,2019,abriria animado apesar aquecer associar batia ...,A: aquecer casa corpos; B: casa corpos entrada...,"[[-0.203611, 0.159881, 0.093636, -0.080348, -0..."
4,95,Glicólise é um processo que ocorre nas células...,A: libera 112 kJ por mol de glicose.; B: liber...,2.21432,A,2019,alguns anaeróbico casos combustão completament...,A: glicose kj libera mol; B: glicose kj libera...,"[[-0.000374, -0.127046, -0.401209, -0.020222, ..."

In [11]:
cleaned_data.to_csv('/content/drive/MyDrive/MED-enem/cleaned_data_vectors.csv')